# Disconet Ansible Collection Requirements
---
collections:
  # Community General - utilities and common modules
  - name: community.general
    version: ">=8.0.0"

  # pfSense management
  - name: pfsensible.core
    version: ">=0.6.0"

  # Proxmox management
  - name: community.proxmox
    version: ">=1.0.0"

  # Network utilities
  - name: ansible.netcommon
    version: ">=6.0.0"

  # Network device modules
  - name: community.network
    version: ">=5.0.0"

  # Zyxel switch management (custom collection)
  # Install from local ansible-zyxel repository using: make install-zyxel-collection
  # This requires the ansible-zyxel repo to be cloned at ../ansible-zyxel
  # Clone with: git clone git@github.com:sandinak/ansible-zyxel.git ../ansible-zyxel

  # POSIX utilities
  - name: ansible.posix
    version: ">=1.5.0"

