# Disconet Inventory
---
all:
  children:
    # pfSense Firewalls
    pfsense:
      hosts:
        # fw01.disconet.local:
        #   ansible_host: 192.168.1.1
      vars:
        ansible_connection: httpapi
        ansible_network_os: pfsensible.core.pfsense
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false

    # Zyxel Switches - All switches
    zyxel:
      children:
        # Core/Distribution switches
        core_switches:
          hosts:
            # sw-core01.disconet.local:
            #   ansible_host: 192.168.10.1
        # IDF Access switches - share common template
        idf_switches:
          hosts:
            # sw-idf01.disconet.local:
            #   ansible_host: 192.168.10.11
            # sw-idf02.disconet.local:
            #   ansible_host: 192.168.10.12
            # sw-idf03.disconet.local:
            #   ansible_host: 192.168.10.13
      vars:
        ansible_connection: network_cli
        ansible_network_os: zyxel
        ansible_become: false

    # Proxmox Hypervisors
    proxmox:
      hosts:
        # pve01.disconet.local:
        #   ansible_host: 192.168.20.1
      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3

    # Proxmox VMs (managed through API)
    proxmox_vms:
      vars:
        ansible_connection: local
