# Disconet Inventory
---
all:
  children:
    # pfSense Firewalls
    pfsense:
      hosts:
        pfsense1.disconet.work:
          ansible_host: 172.19.1.252
        pfsense2.disconet.work:
          ansible_host: 172.19.1.253
      vars:
        ansible_connection: httpapi
        ansible_network_os: pfsensible.core.pfsense
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false

    # Zyxel Switches - All switches
    zyxel:
      children:
        # Core/Distribution switches
        core_switches:
          hosts:
            sw-core1.disconet.work:
              ansible_host: 172.19.1.15
              switch_model: GS1915-24EP
            sw-core2.disconet.work:
              ansible_host: 172.19.1.16
              switch_model: GS1915-24EP
        # IDF Access switches - share common template
        idf_switches:
          hosts:
            sw-idf1.disconet.work:
              ansible_host: 172.19.1.17
              switch_model: GS1920-24HP
            sw-idf2.disconet.work:
              ansible_host: 172.19.1.18
              switch_model: GS1920-24HP
            sw-idf3.disconet.work:
              ansible_host: 172.19.1.19
              switch_model: GS1920-24HP
        # Podium switches
        podium_switches:
          hosts:
            sw-pod1.disconet.work:
              ansible_host: 172.19.1.20
              switch_model: GS1900-8HP
            sw-pod2.disconet.work:
              ansible_host: 172.19.1.21
              switch_model: GS1900-8HP
            sw-pod3.disconet.work:
              ansible_host: 172.19.1.22
              switch_model: GS1900-8HP
            sw-junk.disconet.work:
              ansible_host: 172.19.1.23
              switch_model: GS1915-24
        # Special purpose switches
        special_switches:
          hosts:
           # sw-junk.disconet.work:
           #   ansible_host: 172.19.1.23
           #   switch_model: GS1915-24
            sw-vov.disconet.work:
              ansible_host: 172.19.1.24
              switch_model: GS1915-24
      vars:
        ansible_connection: network_cli
        ansible_network_os: zyxel
        ansible_become: false

    # Golden Config Reference Switches
    # These are the authoritative sources for their switch type
    # Use: ansible-playbook playbooks/pull_golden_config.yml -l golden_config
    golden_config:
      hosts:
        sw-idf1.disconet.work:
          golden_config_for: idf_switches
          golden_template_file: group_vars/idf_switches.yml
        sw-pod1.disconet.work:
          golden_config_for: podium_switches
          golden_template_file: group_vars/podium_switches.yml
        sw-core1.disconet.work:
          golden_config_for: core_switches
          golden_template_file: group_vars/core_switches.yml
        sw-junk.disconet.work:
          golden_config_for: special_switches
          golden_template_file: group_vars/special_switches.yml

    # Proxmox Hypervisors
    proxmox:
      hosts:
        pve.disconet.work:
          ansible_host: 172.19.1.30
      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3

    # Proxmox VMs (managed through API)
    proxmox_vms:
      vars:
        ansible_connection: local

    # Network Equipment (Peplink)
    peplink:
      hosts:
        peplink.disconet.work:
          ansible_host: 172.19.0.1
